ennuiFighter/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^games/',include('games.urls'))

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

games/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'games'
urlpatterns = [

    url(r'^$', views.IndexView.as_view(),name='index'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view() ,name='detail'),

    #add
    url(r'paczka/add/$',views.PaczkaCreate.as_view(),name='paczka-add'),
    url(r'paczka/gra/$', views.GraCreate.as_view(), name='gra-add'),
    #update
    url(r'paczka/(?P<pk>[0-9]+)/$',views.PaczkaUpdate.as_view(),name='paczka-update'),
    #delete
    url(r'paczka/(?P<pk>[0-9]+)/delete/$',views.PaczkaDelete.as_view(),name='paczka-delete'),

    url(r'^login/$',views.login,name='login'),
    url(r'^auth/$',views.auth,name='auth'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^loggedin/$',views.loggedin,name='loggedin'),
    url(r'^invalid_login/$',views.invalid_login,name='invalid_login'),
    url(r'^gra_add/$', views.gra_add, name='gra_add'),

]

games/models.py
from django.db import models
from django.core.urlresolvers import reverse

class PaczkaGier(models.Model):
    kreator_paczki = models.CharField(max_length=250)
    nazwa_paczki = models.CharField(max_length=100)
    rodzaj_gier = models.CharField(max_length=100)
    logo_paczki = models.FileField()

    def get_absolute_url(self):
        return reverse('games:detail',kwargs = {'pk':self.pk} )

    def __str__(self):
        return self.kreator_paczki + ': ' + self.nazwa_paczki + '-> ' + self.rodzaj_gier
    def getName(self):
        return self.nazwa_paczki

class Gra(models.Model):
    paczka = models.ForeignKey(PaczkaGier,on_delete=models.CASCADE)
    link_do_pobierania = models.CharField(max_length=200)
    nazwa_gry = models.CharField(max_length=200)
    jest_ulubiona=models.BooleanField(default=False)
    def __str__(self):
        return self.nazwa_gry + ': ' + self.paczka.getName() + '-> ' + self.link_do_pobierania

games/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password =forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=['username','email','password']

games/views.py
from django.views import generic
from .models import PaczkaGier,Gra
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect,render_to_response
from django.contrib.auth import authenticate,login
from django.views.generic import View
from .forms import UserForm
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib import auth
from django.contrib.auth import logout



class IndexView(generic.ListView):
    template_name = 'games/index.html'
    context_object_name = 'all_games'
    def  get_queryset(self):
        return PaczkaGier.objects.all()


class DetailView(generic.DetailView):
    model=PaczkaGier
    context_object_name = 'paczka'
    template_name = 'games/detail.html'



class PaczkaCreate(CreateView):
    model= PaczkaGier
    fields = [ 'kreator_paczki', 'nazwa_paczki' , 'rodzaj_gier' , 'logo_paczki']

class PaczkaUpdate(UpdateView):
    model= PaczkaGier
    fields = [ 'kreator_paczki', 'nazwa_paczki' , 'rodzaj_gier' , 'logo_paczki']

class PaczkaDelete(DeleteView):
    model=PaczkaGier
    success_url = reverse_lazy('games:index')

class GraCreate(CreateView):
    model= Gra
    fields = [ 'paczka','link_do_pobierania', 'nazwa_gry' , 'jest_ulubiona']


class UserFormView(View):
    form_class = UserForm
    template_name='games/registration_form.html'

    def get(self,request):
        form =self.form_class(None)
        return render(request,self.template_name, {'form':form})

    def post(self,request):
        form =self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('games:index')
        return render(request,self.template_name, {'form':form})

def login(request):
    # c={}
    # c.update(request)
    return render(request,'games/login.html')


def auth(request):

    # return render(request,'games/auth.html')
     username=request.POST.get('username','')
     password=request.POST.get('password','')
     uzytkownik=authenticate(username=username,password=password)
     # user = auth.authenticate(username=username,password=password)
     if uzytkownik is not None:
         login(request)
        # login(request,dupa,None)
         # login(request,dupa)
         #return HttpResponseRedirect('/games/logout')
         return render(request,'games/loggedin.html')
     else:
         return render(request,'games/logout.html')

def loggedin(request):
    return render_to_response('loggedin.html',{'full_name': request.user.username})

def invalid_login(request):

    return render_to_response('invalid_login.html')

def logout(request):
    auth.logout(request)
    return render_to_response('logout.html')

def gra_add(request):
    return render(request,'games/gra_add')

games/templates/games/auth.html
{% extends 'games/base.html' %}
{% block title %} Logowanie {%endblock%}

{% block body %}



        <label ><h3>Anawet nie wiem  </h3> </label>

        <!--<input type="reset"   value="log me out">-->

{% endblock %}

games/templates/games/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}eF{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>-->
    <link rel="stylesheet" type="text/css" href="{% static 'games/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="{% static 'games/js/main.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-field">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
            <a class="navbar-brand" href="{% url 'games:index' %}">eF</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">

                <li class="">
                    <a href="{% url 'games:index' %}">
                        <span class="glyphicon glyphicon-inbox" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>

                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-knight" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>


            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'games:paczka-add' %} ">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; dodaj paczke
                    </a>
                </li>


            <li class="">
                    <a href="{% url 'games:login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logowania
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

games/templates/games/detail.html
{% extends 'games/base.html' %}
{% block title %} Paczka {%endblock%}



{% block body %}
    <div class="container-fluid games-container">
        <div class="row">
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <img src="{{paczka.logo_paczki.url}}"  height="200" width="200" class="img-responsive" >
                        <h3 class="text-reponsive" ><Strong>{{ paczka.nazwa_paczki }}</Strong></h3>
                        <h3>{{ paczka.kreator_paczki }}</h3>
                        <h3>{{ paczka.rodzaj_gier }}</h3>

                    </div>

                </div>
            </div>

            <div class="col-sm-8 col-md-9">

                        <ul class="nav nav-pills" style="margin-bottom: 10px;">
                            <li role="presentation"><a href="{% url 'games:gra-add' %} ">Add New Game</a></li>
                        </ul>

                    <div class="panel panel-default">
                        <div class="panel-body">

                            <h3>All Games</h3>

                            {% if error_message %}
                                <p><strong>{{ error_message }}</strong></p>
                            {% endif %}

                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Link</th>
                                    <th>Favorite</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for giera in paczka.gra_set.all %}
                                    <tr>
                                        <td>{{ giera.nazwa_gry}}</td>
                                        <td>
                                            <a target="_blank" href="{{ giera.link_do_pobierania }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-hand-left"></span>&nbsp; Otwórz Link
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if giera.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                        <td>

                                            <form action="#" method="post" style="display: inline;">
                                                {% csrf_token %}
                                                <input type="hidden" name="giera_id" value="{{ giera.id }}" />
                                                <button type="submit" class="btn btn-danger btn-xs">
                                                    <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>

                        </div>
                    </div>

                </div>
        </div>
    </div>




{%endblock%}

games/templates/games/form-template.html
{% for field in form  %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small"{{field.errors}}></span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

games/templates/games/gra_form.html
{% extends 'games/base.html' %}
{% block title  %}Dodaj nowa paczke{% endblock%}
{% block paczka_active %}aktywny{% endblock %}

{% block body %}
<div class=" container-fluid">
    <div class ="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class ="panel-body">
                    <form class ="form-horizontal" action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        {% include 'games/form-template.html' %}
                        <div class ="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Stwórz</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



</div>
{% endblock %}

games/templates/games/index.html
{% extends 'games/base.html' %}
{% block title %} Paczki {%endblock%}
{% block body %}
<div class="paczka_giers-container container-fluid">

    <!-- paczka_giers -->
    <div class="row">
        <div class="col-sm-12">
        </div>
        {% if all_games %}
            {% for paczka_gier in all_games %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'games:detail' paczka_gier.id %}">
                            <img src="{{ paczka_gier.logo_paczki.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h3>{{ paczka_gier.nazwa_paczki }}</h3>
                            <h4>{{ paczka_gier.kreator_paczki }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'games:detail' paczka_gier.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete paczka_gier -->
                            <form action="{% url 'games:paczka-delete' paczka_gier.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="paczka_gier_id" value="{{ paczka_gier.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite paczka_gier -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star {% if paczka_gier.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an paczka_gier
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are games -->
    {% if games %}
        <div class="row">
            <div class="col-sm-12">
                <h3>games</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>game Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>paczka_gier</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for game in games %}
                                    <tr>
                                        <td>{{ game.game_title }}</td>
                                        <td>{{ game.paczka_gier.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ game.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'games:detail' game.paczka_gier.id %}">
                                                <img src="{{ game.paczka_gier.paczka_gier_logo_paczki }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'games:detail' game.paczka_gier.id %}">{{ game.paczka_gier.paczka_gier_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'games:favorite' game.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if game.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

games/templates/games/invalid_login.html
{% extends 'games/base.html' %}
{% block title %} Paczka {%endblock%}

{% block body %}

<h2> Your login or password is valid</h2>


{%endblock%}

games/templates/games/loggedin.html
{% extends 'games/base.html' %}
{% block title %} Paczka {%endblock%}



{% block body %}
    <h2>Hi {{full_name}} you are logged in!</h2>
<!--<p Click <a href ="/games/logout">here</a>to logout</p>-->



{%endblock%}

games/templates/games/login.html
{% extends 'games/base.html' %}
{% block title %} Logowanie {%endblock%}

{% block body %}

    {% if form.errors %}
        <p class ="error">Sorry </p>
    {% endif %}
    <form action="{% url 'games:auth' %}" method="post" >{% csrf_token %}
        <label for="username"><h3>Nazwa Użytkownika: </h3> </label>
        <input type="text" name="username" value="" id="username">
        <br>
        <label for ="password"><h3>Hasło:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </h3></label>
        <input type ="password" name="password" value="" id ="password">
        <br>
        <input type="submit"   value="log me in ">

        <!--<input type="reset"   value="log me out">-->
    </form>
{% endblock %}

games/templates/games/logout.html
{% extends 'games/base.html' %}
{% block title %} Paczka {%endblock%}



{% block body %}
    <h2>something go wrong :login or password!</h2>
<!--<p Click <a href ="/games/logout">here</a>to logout</p>-->



{%endblock%}

games/templates/games/paczkagier_form.html
{% extends 'games/base.html' %}
{% block title  %}Dodaj nowa paczke{% endblock%}
{% block paczka_active %}aktywny{% endblock %}

{% block body %}
<div class=" container-fluid">
    <div class ="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class ="panel-body">
                    <form class ="form-horizontal" action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        {% include 'games/form-template.html' %}
                        <div class ="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Stwórz</button>
                            </div>
                        </div>
                    </form>

                </div>

            </div>


        </div>



    </div>



</div>
{% endblock %}

games/templates/games/registration_form.html
{% extends 'games/base.html' %}
{% block title  %}Register{% endblock%}

{% block body %}
<div class=" container-fluid">
    <div class ="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class ="panel-body">
                    <form class ="form-horizontal" action="" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}
                        {% include 'games/form-template.html' %}
                        <div class ="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Stwórz</button>
                            </div>
                        </div>
                    </form>

                </div>

            </div>


        </div>



    </div>



</div>
{% endblock %}